import Navbar from '@/components/Navbar/Navbar';
import '../../styles/globals.css';
import { Instrument_Sans } from 'next/font/google';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

const instrument_sans = Instrument_Sans({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={`${instrument_sans.className} min-h-screen bg-[#fafafa]`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
